name: 'Update NBViewer Links'

description: >
    A GitHub Action to update NBViewer links in a README file.

author: 'KensingtonOscupant'

inputs:
  commit_email:
    description: 'The email address to use for committing.'
    required: false
  commit_username:
    description: 'The username to use for committing.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email "${{ inputs.commit_email || 'github.actions@example.com' }}"
        git config --global user.name "${{ inputs.commit_username || 'NBViewerLinkBot' }}"
    - name: Update Links in README
      shell: bash
      run: |
        # Get the latest commit hash
        latest_commit="$(git rev-parse main)"

        # Update links in README to include the latest commit
        sed -i "s|https://nbviewer.org/github/\([^/]\+\)/\([^/]\+\)/blob/\([^/]\+\)/\([^' ']\+\)|https://nbviewer.org/github/\1/\2/blob/${latest_commit}/\4|g" README.md

        # Commit and push changes
        git add README.md
        git commit -m "Update NBViewer links to latest commit"
        git push
